### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by adolfdsilva** [medyo/Fancybuttons#41]
Hi can you please tel me why I'm getting class cast exception, it seems to work fine in another activity.

12-02 23:54:31.010 27853-27853/outletwise.com.twentydresses E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: outletwise.com.twentydresses, PID: 27853
                                                                              java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.RelativeLayout$LayoutParams
                                                                                  at android.widget.RelativeLayout$DependencyGraph.findRoots(RelativeLayout.java:1722)
                                                                                  at android.widget.RelativeLayout$DependencyGraph.getSortedViews(RelativeLayout.java:1667)
                                                                                  at android.widget.RelativeLayout.sortChildren(RelativeLayout.java:373)
                                                                                  at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:381)
                                                                                  at android.view.View.measure(View.java:16543)
                                                                                  at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1241)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                  at android.widget.ScrollView.onMeasure(ScrollView.java:326)
                                                                                  at android.view.View.measure(View.java:16543)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                  at android.support.v7.widget.CardView.onMeasure(CardView.java:196)
                                                                                  at android.view.View.measure(View.java:16543)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                  at android.view.View.measure(View.java:16543)
                                                                                  at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
                                                                                  at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
                                                                                  at android.view.View.measure(View.java:16543)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                  at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                                  at android.view.View.measure(View.java:16543)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
                                                                                  at android.view.View.measure(View.java:16543)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                  at android.view.View.measure(View.java:16543)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
                                                                                  at android.view.View.measure(View.java:16543)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5147)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                  at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2327)
                                                                                  at android.view.View.measure(View.java:16543)
                                                                                  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1979)
                                                                                  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1140)
                                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1331)
                                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1027)
                                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5884)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:593)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:562)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
                                                                                  at android.os.Handler.handleCallback(Handler.java:733)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:136)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5253)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by medyo** [comment]
Hi @adolfdsilva,

Could you share with us your xml layout and java code ?

**Comment by adolfdsilva** [comment]
Ya I think I got the error. If you remove the text attribute
            fancy:fb_text="test"
It crashes, does the button need a default fb_text value?
Below is my code

 <mehdi.sakout.fancybuttons.FancyButton
            android:id="@+id/bConfirmed"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_below="@+id/tvOrderNo"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="8dp"
            android:paddingBottom="8dp"
            android:paddingLeft="44dp"
            android:paddingRight="44dp"
            android:paddingTop="8dp"
            fancy:fb_borderColor="@color/md_yellow_700"
            fancy:fb_borderWidth="1dp"
            fancy:fb_defaultColor="@android:color/transparent"
            fancy:fb_focusColor="@color/md_grey_300"
            fancy:fb_radius="6dp"
            fancy:fb_text="@string/button_confirmed"
            fancy:fb_textColor="@color/md_yellow_700" />

**Comment by medyo** [comment]
According to your code, I don't see any filling value (text or icon). Make sure you add one or if you want an empty button, just set `fancy:fb_text=""`

**Comment by adolfdsilva** [comment]
Ok,so one of this is necessary while inflating, you can't directly set it at run time.

**Comment by PGMacDesign** [comment]
As a heads up, I followed these steps and faced the same problem. If I had it within a Relative Layout, it would break and throw this exception. If I had it outside of the layout, it would work just fine. I finally had to set everything statically within the xml and then change the text dynamically to get it to work.
